python task1.py --num-topics 1 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 2 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 3 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 4 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 5 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 6 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 7 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 8 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 9 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 10 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 11 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 12 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 13 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 14 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 15 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 16 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 17 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 18 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 19 --data-dir polusa_balanced --out-dir polusa_balanced
python task1.py --num-topics 20 --data-dir polusa_balanced --out-dir polusa_balanced